name: "Get & Cache Dependencies"
description: "Get code and cache dependencies for the workflow"
inputs:
  caching:
    description: "Wether to cache dependencies or not"
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Indicates if the cache was used"
    value: ${{ steps.install }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "$GITHUB_OUTPUT name=cache::'${{ inputs.caching }}'"
      shell: bash
